DECLARE @OurListOfForeignKeyConstraints  NVARCHAR(MAX)
EXECUTE #ListAllForeignKeyConstraints @TheJsonList=@OurListOfForeignKeyConstraints OUTPUT
SELECT @OurListOfForeignKeyConstraints AS theForeignKeyConstraints